import type { NextPage } from "next";
import Head from "next/head";
import FixedHeader from "../../components/FixedHeader";
import SectionHeader from "../../components/SectionHeader";
import { useQuery } from "@apollo/client";
import { useRouter } from "next/router";
import { gql } from "@apollo/client";
import { documentToReactComponents } from "@contentful/rich-text-react-renderer";
import Contact from "../../components/Contact";

const Slug: NextPage = () => {
  const router = useRouter();
  const { slug } = router.query;

  const GET_POST = gql`
    query GetPostBySlug($slug: String!) {
      blogPostCollection(where: { slug: $slug }, limit: 1) {
        items {
          title
          slug
          featuredImage {
            title
            url
          }
          content {
            json
          }
        }
      }
    }
  `;

  const { loading, error, data } = useQuery(GET_POST, {
    variables: { slug },
  });

  if (loading) return "Loading...";
  if (error) return `Error! ${error.message}`;

  return (
    <>
      <Head>
        <title>Billy Arnold</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="shortcut icon"
          href="/faviconNew.png"
          type="image/x-icon"
        ></link>
        <link rel="icon" href="/faviconNew.png" type="image/x-icon"></link>
      </Head>

      <FixedHeader />

      <div className="fixed-header-spacer h-4 lg:hidden"></div>
      <SectionHeader>Freelance Developer Based in Kent</SectionHeader>

      <div className="uppercase w-full px-5 md:px-20 pb-10 font-semibold text-4xl sm:text-6xl md:text-7xl lg:text-8xl xl:text-9xl">
        <h1 className="mb-6">{data.blogPostCollection.items[0].title}</h1>
      </div>

      <div className="uppercase w-full px-5 md:px-20 pb-12">
        <img
          src={data.blogPostCollection.items[0].featuredImage.url}
          className="w-full"
        />
      </div>

      <div className="w-full px-5 md:px-20 flex flex-col blog-content">
        {documentToReactComponents(
          data.blogPostCollection.items[0].content.json
        )}
      </div>

      <Contact lineOne="HELLO@BILLY" lineTwo="ARNOLD.CO.UK" />
    </>
  );
};

export default Slug;
