import type { NextPage } from "next";
import Head from "next/head";
import FixedHeader from "../components/FixedHeader";
import SectionHeader from "../components/SectionHeader";
import LargeHeading from "../components/LargeHeading";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Billy Arnold</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="shortcut icon"
          href="/faviconNew.png"
          type="image/x-icon"
        ></link>
        <link rel="icon" href="/faviconNew.png" type="image/x-icon"></link>
      </Head>

      <FixedHeader />

      <div className="fixed-header-spacer h-4 lg:hidden"></div>
      <SectionHeader>Freelance Developer Based in Kent</SectionHeader>

      <LargeHeading
        lineOne="BILLY"
        lineTwo="ARNOLD"
        className="justify-start"
      />
    </>
  );
};

export default Home;

export async function getStaticProps() {}
