import type { NextPage } from "next";
import Head from "next/head";
import FixedHeader from "../components/FixedHeader";
import SectionHeader from "../components/SectionHeader";
import LargeHeading from "../components/LargeHeading";
import { useQuery } from "@apollo/client";
import GET_POSTS from "../../queries/getPosts";
import BlogItem from "../components/blogItem";
import Contact from "../components/Contact";
import { itemType } from "../components/blogItem";

const Home: NextPage = () => {
  const { loading, error, data } = useQuery(GET_POSTS);

  if (loading)
    return (
      <div>
        <p>Loading...</p>
      </div>
    );
  if (error)
    return (
      <div>
        <p>Error! {error.message}</p>
      </div>
    );

  return (
    <>
      <Head>
        <title>Billy Arnold</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="shortcut icon"
          href="/faviconNew.png"
          type="image/x-icon"
        ></link>
        <link rel="icon" href="/faviconNew.png" type="image/x-icon"></link>
      </Head>

      <FixedHeader />

      <div className="fixed-header-spacer h-4 lg:hidden"></div>
      <SectionHeader>Freelance Developer Based in Kent</SectionHeader>

      <LargeHeading
        lineOne="BILLY"
        lineTwo="ARNOLD"
        className="justify-start"
      />

      <div className="w-full px-5 md:px-20">
        {data.blogPostCollection.items.map((item: itemType["item"]) => (
          <BlogItem item={item} />
        ))}
      </div>

      <Contact lineOne="HELLO@BILLY" lineTwo="ARNOLD.CO.UK" />
    </>
  );
};

export default Home;
